// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA58oGRM2YJAc00IqppSuJxheevekUnuZQ',
    appId: '1:853507749033:web:a1e3a17af2291a66eea5b8',
    messagingSenderId: '853507749033',
    projectId: 'nomino-c8c6b',
    authDomain: 'nomino-c8c6b.firebaseapp.com',
    storageBucket: 'nomino-c8c6b.firebasestorage.app',
    measurementId: 'G-77TQC12RGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3JYOWu7Qne7NSetqwzyJe26jSWINsVLQ',
    appId: '1:853507749033:android:48cf423b86259ef6eea5b8',
    messagingSenderId: '853507749033',
    projectId: 'nomino-c8c6b',
    storageBucket: 'nomino-c8c6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMsYcW8FxU2BYQ1CjInb8kNCGxjfizg1o',
    appId: '1:853507749033:ios:29b2092f3ccc434eeea5b8',
    messagingSenderId: '853507749033',
    projectId: 'nomino-c8c6b',
    storageBucket: 'nomino-c8c6b.firebasestorage.app',
    iosBundleId: 'com.meshach.nomino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMsYcW8FxU2BYQ1CjInb8kNCGxjfizg1o',
    appId: '1:853507749033:ios:7675328854738823eea5b8',
    messagingSenderId: '853507749033',
    projectId: 'nomino-c8c6b',
    storageBucket: 'nomino-c8c6b.firebasestorage.app',
    iosBundleId: 'com.example.nomino',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA58oGRM2YJAc00IqppSuJxheevekUnuZQ',
    appId: '1:853507749033:web:775d8f181b8a2c64eea5b8',
    messagingSenderId: '853507749033',
    projectId: 'nomino-c8c6b',
    authDomain: 'nomino-c8c6b.firebaseapp.com',
    storageBucket: 'nomino-c8c6b.firebasestorage.app',
    measurementId: 'G-28F5C79EG0',
  );
}
